package UserCreditionals;


import java.sql.*;

/**
 *
 * @author phani
 */
public class BankBalance extends javax.swing.JFrame {

     /**
      * Creates new form Balance
      */
     public BankBalance()
     {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is always
      * regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          back = new javax.swing.JButton();
          jLabel2 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
          jLabel1.setText("BANK BALANCE");

          back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow_back_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
          back.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    backActionPerformed(evt);
               }
          });

          jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
          jLabel2.setText("REMAINING BALANCE IS ->");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addGap(150, 150, 150)
                                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addGap(52, 52, 52)
                                                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addGap(311, 311, 311)
                                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(182, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(114, 114, 114)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(361, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>

     public void SetText(String bal)
     {
          jLabel2.setText("REMAINIG BALANCE IS -> "+bal);
     }
     private void backActionPerformed(java.awt.event.ActionEvent evt)
     {
          HomeForm hf = new HomeForm() ;
          hf.setVisible(true);
          this.dispose();
     }

     // Variables declaration - do not modify
     private javax.swing.JButton back;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     // End of variables declaration
}
class Balance
{
     String CardNumber ;
     String Pin ;
     Balance(String CardNumber,String Pin)
     {
          this.CardNumber = CardNumber ;
          this.Pin = Pin ;
     }
     public String Balance()
     {
          String Balance = "" ;
          String TableName = HomeForm.MobileNumber+"_cardbalance" ;
          try
          {
             Class.forName(DataBaseDetails.driver) ;
             Connection con = DriverManager.getConnection(DataBaseDetails.url,DataBaseDetails.un,DataBaseDetails.pwd) ;
               PreparedStatement ps = con.prepareStatement("select * from "+TableName+" where CardNumber=? and Pin=?") ;
               ps.setString(1,CardNumber);
               ps.setString(2,Pin);
               ResultSet rs = ps.executeQuery() ;
               if(rs.next())
               {
                    Balance = rs.getString(3) ;
               }
               ps.close();
               con.close();
          }
          catch (SQLException sql)
          {
               sql.printStackTrace();
          } catch (ClassNotFoundException e) {
               e.printStackTrace();
          }
          return Balance ;
     }
}