package UserCreditionals;

import javax.swing.*;

/**
 *
 * @author phani
 */
public class ForgetDetails extends javax.swing.JFrame {

     /**
      * Creates new form ForgetDetails
      */
     String form = "Login" ;
     public ForgetDetails()
     {
          initComponents();
     }
     public ForgetDetails(String form)
     {
          initComponents();
          this.form = form ;
     }
     /**
      * This method is called from within the constructor to initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is always
      * regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          Back = new javax.swing.JButton();
          Enter = new javax.swing.JButton();
          Email = new javax.swing.JTextField();
          jLabel2 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
          jLabel1.setText("Forget Details");

          Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow_back_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
          Back.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BackActionPerformed(evt);
               }
          });

          Enter.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
          Enter.setText("Enter");
          Enter.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    EnterActionPerformed(evt);
               }
          });

          jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
          jLabel2.setText("Email");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addGap(75, 75, 75)
                                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addGap(50, 50, 50)
                                                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addGap(362, 362, 362)
                                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(28, 28, 28)
                                                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(400, Short.MAX_VALUE))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(419, 419, 419))
          );
          layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(109, 109, 109)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                  .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(66, 66, 66)
                                        .addComponent(Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(277, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>

     private void EnterActionPerformed(java.awt.event.ActionEvent evt)
     {
          /**
           Here we have to check whether the given entered email is in the database or not
           if it is there we can allow to update their Password....
           To check whether the given mail id is exist in the database we have to first check
           whether the given mail Id exists or not...
           */
          if(new RegExCheck(Email.getText()).EmailCheck())
          {
               if(new CheckingDetails(Email.getText()).DataBaseEmailChecker())
               {
                    /***
                     here we will call another JFrame where it takes the
                     Password from the User and Checks it's Correct Choice or not
                     and it will Call the UpdatePassword function in the Checking Details
                     class.
                     */
                    if(form.equals("Login")) {
                         ChoosePassWord sp = new ChoosePassWord(form, Email.getText());
                         sp.setVisible(true);
                         this.dispose();
                    }
                    else
                    {
                         ChoosePassWord sp = new ChoosePassWord(form, Email.getText());
                         sp.setVisible(true);
                         this.dispose();
                    }

               }
               else
               {
                    JOptionPane.showMessageDialog(this,"InCorrect Mail-Id");
               }
          }
          else
          {
               JOptionPane.showMessageDialog(this,"Invalid Mail-Id");
          }
     }

     private void BackActionPerformed(java.awt.event.ActionEvent evt)
     {
         if(form=="Login")
         {
              LoginForm l = new LoginForm() ;
              l.setVisible(true);
              this.dispose();
         }
         else
         {
              Settings st = new Settings() ;
              st.setVisible(true) ;
              this.dispose() ;
         }
     }


     // Variables declaration - do not modify
     private javax.swing.JButton Back;
     private javax.swing.JTextField Email;
     private javax.swing.JButton Enter;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     // End of variables declaration
}
