package UserCreditionals;


/**
 *
 * @author phani
 */
public class Settings extends javax.swing.JFrame
{

     /**
      * Creates new form Settings
      */
     public Settings() {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is always
      * regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          ForgetKey = new javax.swing.JButton();
          exit = new javax.swing.JButton();
          Log_Out = new javax.swing.JButton();
          close = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
          jLabel1.setText("Settings");

          ForgetKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
          ForgetKey.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ForgetKeyActionPerformed(evt);
               }
          });

          exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit_to_app_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
          exit.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitActionPerformed(evt);
               }
          });

          Log_Out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
          Log_Out.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Log_OutActionPerformed(evt);
               }
          });

          close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
          close.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    closeActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(ForgetKey, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                      .addGroup(layout.createSequentialGroup()
                                                                                .addGap(107, 107, 107)
                                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                      .addGroup(layout.createSequentialGroup()
                                                                                .addGap(213, 213, 213)
                                                                                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                  .addGroup(layout.createSequentialGroup()
                                                            .addGap(42, 42, 42)
                                                            .addComponent(close)))
                                        .addContainerGap(774, Short.MAX_VALUE))
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                  .addGap(210, 210, 210)
                                                  .addComponent(Log_Out, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addContainerGap(777, Short.MAX_VALUE)))
          );
          layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(163, 163, 163)
                                        .addComponent(ForgetKey, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(227, Short.MAX_VALUE))
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                  .addGap(227, 227, 227)
                                                  .addComponent(Log_Out, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addContainerGap(411, Short.MAX_VALUE)))
          );

          pack();
     }// </editor-fold>

     private void Log_OutActionPerformed(java.awt.event.ActionEvent evt)
     {
          MyPage.Main() ;
          this.dispose() ;
     }

     private void closeActionPerformed(java.awt.event.ActionEvent evt)
     {
          HomeForm hf = new HomeForm() ;
          hf.setVisible(true);
          this.dispose();
     }

     private void ForgetKeyActionPerformed(java.awt.event.ActionEvent evt)
     {
          ForgetDetails fd = new ForgetDetails("Settings") ;
          fd.setVisible(true) ;
          this.dispose() ;
     }

     private void exitActionPerformed(java.awt.event.ActionEvent evt)
     {
          System.exit(0);
     }


     // Variables declaration - do not modify
     private javax.swing.JButton ForgetKey;
     private javax.swing.JButton Log_Out;
     private javax.swing.JButton close;
     private javax.swing.JButton exit;
     private javax.swing.JLabel jLabel1;
     // End of variables declaration
}
