package UserCreditionals;


/**
 *
 * @author phani
 */

import javax.swing.*;
import java.sql.*;

/**
      *
      * @author phani
      */
     public class Wallet extends javax.swing.JFrame {

          /**
           * Creates new form Wallet
           */
          public Wallet()
          {
               initComponents();
          }

          /**
           * This method is called from within the constructor to initialize the form.
           * WARNING: Do NOT modify this code. The content of this method is always
           * regenerated by the Form Editor.
           */
          @SuppressWarnings("unchecked")
          // <editor-fold defaultstate="collapsed" desc="Generated Code">
          private void initComponents() {

               jScrollPane1 = new javax.swing.JScrollPane();
               jLabel1 = new javax.swing.JLabel();
               balance = new javax.swing.JLabel();
               jLabel2 = new javax.swing.JLabel();
               topUp = new javax.swing.JButton();
               Back = new javax.swing.JToggleButton();

               setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

               jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
               jLabel1.setText("Welcome to the Wallet of E-Banking");

               balance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
               balance.setText("Wallet Balance : 0");

               jLabel2.setText("TO TOP-UP Click This Button");

               topUp.setText("TopUp");
               topUp.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                         topUpActionPerformed(evt);
                    }
               });

               Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow_back_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
               Back.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                         BackActionPerformed(evt);
                    }
               });

               javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
               getContentPane().setLayout(layout);
               layout.setHorizontalGroup(
                         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addGroup(layout.createSequentialGroup()
                                                                 .addGap(87, 87, 87)
                                                                 .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGroup(layout.createSequentialGroup()
                                                                 .addGap(322, 322, 322)
                                                                 .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGroup(layout.createSequentialGroup()
                                                                 .addGap(314, 314, 314)
                                                                 .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                 .addComponent(topUp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGroup(layout.createSequentialGroup()
                                                                 .addContainerGap()
                                                                 .addComponent(Back)))
                                             .addContainerGap(536, Short.MAX_VALUE))
               );
               layout.setVerticalGroup(
                         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                             .addContainerGap()
                                             .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGap(27, 27, 27)
                                             .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGap(113, 113, 113)
                                             .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGap(35, 35, 35)
                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(topUp))
                                             .addContainerGap(346, Short.MAX_VALUE))
               );

               pack();
          }// </editor-fold>

          private void topUpActionPerformed(java.awt.event.ActionEvent evt) {
              // balance = new JLabel("1") ;
             //  balance.setText("Wallet Balance : 10000000000000000000000000000000000000000000000000");
              // this.add(balance) ;
               dbms d = new dbms() ;
               if(d.dbms())
               {
                    SelectCard sc = new SelectCard() ;
                    sc.setVisible(true);
                    this.dispose();
               }
               else
               {
                    AddAccount ad = new AddAccount() ;
                    ad.setVisible(true);
                    this.dispose();
               }

          }

          private void BackActionPerformed(java.awt.event.ActionEvent evt)
          {
               HomeForm hf = new HomeForm() ;
               hf.setVisible(true);
               this.dispose();
          }
     public void setBalance(String Balance)
     {
          balance.setText("Wallet Balance : "+Balance);

     }

          /**
           * @param args the command line arguments
           */


          // Variables declaration - do not modify
          private javax.swing.JToggleButton Back;
          private javax.swing.JLabel balance;
          private javax.swing.JLabel jLabel1;
          private javax.swing.JLabel jLabel2;
          private javax.swing.JScrollPane jScrollPane1;
          private javax.swing.JButton topUp;
          // End of variables declaration
     }
class dbms
{
     public boolean dbms()
     {
          try
          {
               Class.forName(DataBaseDetails.driver) ;
               Connection con = DriverManager.getConnection(DataBaseDetails.url,DataBaseDetails.un,DataBaseDetails.pwd) ;
               Statement st = con.createStatement();
               String s = HomeForm.MobileNumber+"_addaccount" ;
               ResultSet rs = st.executeQuery("select * from "+s) ;
               if(rs.next())
               {
                    return true ;
               }
               else
               {
                    return false ;
               }
          }
          catch (SQLException sql)
          {

          } catch (ClassNotFoundException e) {
               e.printStackTrace();
          }
          return false ;
     }
     public  String WalletBalance()
     {
          String Balance = "" ;
          try
          {
               Class.forName(DataBaseDetails.driver) ;
               Connection con = DriverManager.getConnection(DataBaseDetails.url,DataBaseDetails.un,DataBaseDetails.pwd) ;
               Statement st = con.createStatement();
              // String s = HomeForm.MobileNumber+"_addaccount" ;
               ResultSet rs = st.executeQuery("select * from e_bankingcreditionals where MOBILENUMBER = "+HomeForm.MobileNumber) ;
               if(rs.next()) Balance = rs.getString(4) ;
               st.close();
               con.close();
          }
          catch (SQLException sql)
          {
               sql.printStackTrace();
          } catch (ClassNotFoundException e) {
               e.printStackTrace();
          }
          return Balance ;
     }
}

